# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env


networks:
  default: development
  development:
    cmd_settings:
      mnemonic: between pilot arrest friend profit agree auction grass giant love ensure require
      default_balance: 100
      # unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
      # # (requires explicit transfer of eth to accounts[-1]) 

    update_interval: 60
    verify: False
  
  kovan:

    verify: False
    update_interval: 60


wallets:
  from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true

compiler:
  solc:
    version: 0.8.2
    remappings:
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.0.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.0.0
